site_name: Alif Yasa
theme:
  name: material
  features:
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7

        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - About Me: index.md
  - Contacts: contacts.md
  - Projects:
      - projects/index.md
  - Work Experiences:
      - work-experiences/index.md
plugins:
  - blog:
      blog_dir: projects
      post_dir: "{blog}/list-of-projects"
      blog_toc: true
      archive: false
  - blog:
      blog_dir: work-experiences
      post_dir: "{blog}/list-of-work-experiences"
  - search
markdown_extensions:
  - attr_list
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alifyasa
      name: Alif Yasa on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alif-yasa
      name: Alif Yasa on LinkedIn
    - icon: fontawesome/solid/envelope
      link: mailto:contact@alifyasa.dev
      name: Send an email to Alif Yasa
